language: node_js
node_js:
- stable
branches:
  only:
  - master
install:
- npm install
before_script:
- git checkout -b gh-pages
script:
- npm run build
after_success:
- cd dist
- git init
- git config user.name 'keika299'
- git config user.email 'keika299@gmail.com'
- git add -A
- git commit -m 'Update'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [
  $GH_TOKEN ] && git push -f https://$GH_TOKEN@github.com/keika299/kiritan-timer.git
  gh-pages'
env:
  global:
  - GIT_COMMITTER_NAME=keika299
  - GIT_COMMITTER_EMAIL=keika299@gmail.com
  - GIT_AUTHOR_NAME=keika299
  - GIT_AUTHOR_EMAIL=keika299@gmail.com
  - secure: "iBlTBIdaUEUyfLDvuM2B+WnGkFE+0+fjNQ+sOuIZnyZLo63mROMYWx6Y1Fn+5yEMpDgFzdkz1ZQoTErFOgqC1jiL+FrtR9tQyakXzCWxWPrhR8dkH3r/XrEVomB4nn44Ojgnc3GkUsjEbhN6oPBIXWMpExe/soENGIyLcW2Ou4fjxlrrMhNL8hHHOTi8cxHVMSu/vZm7ifjEWzH5dFHpTRLvZWsTE9Kpfnz651c6BmB+et0kKhWMJzedbd8Y4Fz2odpfS6YEgKtkXYwZ2YPqPEhxgNz3E2zKI4VJEujesgH65xBK8VzHcF6wQjjvuqCGwVEvofSOw5xlJJhFb8SQnQ8s16q/pe4iSF8vbAFyfj7WcuLuWJIoplJSFHCil7p/I7ZJSmONIOFWNH/8Qr5qUQcPsJj0F7P6fXqlYwTSnGIQ7wBDUeL59tt8JOv05Y6peKIDkqzydaQ2KSJxWCni9PKUSsqihBclEirc4SpecKBkXgK3GArkjyzcNVihZJ8SPjTSRf87V+Cyq74BkxYYip+QhNRZvHwwmDC6HlKNrp4PseJAmjeEsFik5ChpKd8F1qW0tJQz0CuSnHA9TbvzfBvqQpRAZUmyrrEnYJAgxLTx2+tTgTJKbWKF52HbnQ3brsTNJ8imf9N1o40iCi0o4M7FQDfcwjd2SQMqF1v/98I="
