language: node_js
node_js:
- stable
branches:
  only:
  - master
install:
- npm install
before_script:
- git checkout -b gh-pages
script:
- npm run build
after_success:
- cd dist
- git init
- git config user.name 'keika299'
- git config user.email 'keika299@gmail.com'
- git add -A
- git commit -m 'Update'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && git
  push --quiet -f https://${GH_TOKEN}@github.com/keika299/kiritan-timer.git master:gh-pages'
env:
  global:
    -secure: "XznEKxHjUWjjTGz9En4Ks6Br6/zt2IPZ5P/bOlJ4t76L7RpLPDTfw/gUjMbWHX0zTs8FAzX15e/tIYvDtkE/hF/+Q6sjPaO6fUbFlXPrTaqUp/F+AChXUUfAueAbDeiEn28lKmozwp5UML39VCRjBF1g4e35AZZt74JQixy8GHh6/4BzmWJKYomQdqyDB64AIVVKJIzoIEsrQLYBNgL5CrG56TluDGSNtohNohd+xCr8AOtinbnusHr5LGq6pKWlAIGNTr7mdMqMHP7Pl8JHpW3KobeMZsX/1qKwp1n9Ws/o9D9Ha/tTpyP55LPZQeB6ClUesHYKqNR7UVKJE+losJfGuM68hVIpT1BJN5tROHUQ98kC8ghjkKZ+f+S8lLPi6TAz6vWDUdhW2kbjygvnp0bGxHuMrh9Q0YLHnM8fOnNuAKKuM7tdCmk01Twj9UJ5tmasP3Jo8fVm5lNgVo/Uzr0KeLtuTA5TGa2e6GCoSNwris5D8Cy7VDT4A4/DJwhz8CTIgkPT8Gd10f/DjpFgaumNkamWFb9tl1049Hu2YC+dApb28us48qZ6izq//nEOv8zpyAaHZBZq9LV9OWoXqzE1/Ukkk7UiLMRgRuz7sf7dvBBBCdclELeCDSI/iwimZ5QdtyOU8ezST1n3F/dKdCcp+suwzsXvXwW8L0Bukj4="
